InvasionTropical_Sorteo/InvasionTropical_Sorteo/urls.py
from django.contrib import admin
from django.urls import path,include

# from participantes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('usuarios.urls')),
    path('participantes/',include('participantes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    
]

InvasionTropical_Sorteo/usuarios/urls.py
from django.urls import path

from .views import bienvenida, home,register_view,salir

app_name='app_usuarios'
urlpatterns = [
    path('',bienvenida,name='bienvenida'),
    path('panel_de_control/',home,name='Home'),
    path('añadir_usuario/',register_view,name='usuario_nuevo'),
    path('salir/',salir, name='salir'),
]

InvasionTropical_Sorteo/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class CamposComunes(models.Model):
    creacion_fecha = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de creación',
    )
    creacion_usuario = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_related",
        related_query_name="%(app_label)s_%(class)ss",
        verbose_name='Usuario de creación',
    )
    modificacion_fecha = models.DateTimeField(
        auto_now=True,
        verbose_name='Fecha de modificación',
    )
    modificacion_usuario = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='Usuario de  modificación',
    )

    def __str__(self):
        return f'{self.creacion_fecha}'

    

InvasionTropical_Sorteo/base/views.py
from django.shortcuts import render

# Create your views here.

InvasionTropical_Sorteo/templates/base/__footer.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
        </div>
    </div>
</footer>

InvasionTropical_Sorteo/templates/base/__navbar.html
<header>
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <h1 class="navbar-brand ps-3 titulo" >Invasion tropical</h1>
            <!-- Navbar-->
            {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4 position-absolute end-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'app_usuarios:salir' %}">Cerrar sesion</a></li>
                    </ul>
                </li>
            </ul>
            {% endif %}
        </nav>
</header>

InvasionTropical_Sorteo/templates/base/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Jonatan Cabrera">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css\styles.css' %}">
	<link rel="stylesheet" href="{% static 'css\estilo.css' %}">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.11.3/b-2.0.1/b-html5-2.0.1/r-2.2.9/datatables.min.css"/>
 

    <title> {%block titulo%}{%endblock%}</title>
</head>
<body>
    <header>
		<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
				<!-- Navbar Brand-->
				<h1 class="navbar-brand ps-3 titulo" >Invasion tropical</h1>
				<!-- Navbar-->
				{% if user.is_authenticated %}
				<ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4 position-absolute end-0">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
						<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="{% url 'app_usuarios:salir' %}">Cerrar sesion</a></li>
						</ul>
					</li>
				</ul>
				{% endif %}
			</nav>
	</header>
	<article>
		{% block contenido %}
			
		{% endblock%}
	</article>
    <footer class="py-4 bg-light mt-auto">
		<div class="container-fluid px-4">
			<div class="d-flex align-items-center justify-content-between small">
				<div class="text-muted">Copyright &copy; Your Website 2021</div>
					<div>
						<a href="#">Privacy Policy</a>
						&middot;
						<a href="#">Terms &amp; Conditions</a>
					</div>
			</div>
		</div>
	</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js\scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.11.3/b-2.0.1/b-html5-2.0.1/r-2.2.9/datatables.min.js"></script>
    <script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>