InvasionTropical_Sorteo/InvasionTropical_Sorteo/urls.py
from django.contrib import admin
from django.urls import path,include

# from participantes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('usuarios.urls')),
    path('participantes/',include('participantes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    
]

InvasionTropical_Sorteo/participantes/urls.py
from django.urls import path
from .views import registrarParticipantes,lista
# from participantes import views
app_name= 'app_participantes'
urlpatterns = [
    path('registro/',registrarParticipantes,name="registro" ),
    path('listadodeventas/',lista,name='lista')

]

InvasionTropical_Sorteo/usuarios/urls.py
from django.urls import path

from .views import bienvenida, home,register_view,salir

app_name='app_usuarios'
urlpatterns = [
    path('',bienvenida,name='bienvenida'),
    path('panel_de_control/',home,name='Home'),
    path('añadir_usuario/',register_view,name='usuario_nuevo'),
    path('salir/',salir, name='salir'),
]

InvasionTropical_Sorteo/templates/formulario/registro.html
{% extends "base/layout.html" %}
{% block titulo %}
	Invasion Tropical | Registrar participante
{% endblock %}
{% block contenido %}
<section>
	<div id="layoutAuthentication">
		<div id="layoutAuthentication_content">
			<main>
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-lg-5">
							<div class="card shadow-lg border-0 rounded-lg mt-5">
								<div class="card-header bg-dark">
									<h3 class="text-center font-weight-light my-4 titulo text-white" >
										Nuevo participante
									</h3>
								</div>
								<div class="card-body">
									{%if mensaje%}
										<div class="alert alert-danger" role="alert">
											{{mensaje}}										
									  	</div>
									  	<form action="{% url 'app_participantes:registro' %}" method="POST">
										{% csrf_token %}
										<div class="form-floating mb-3 formulario">
											{{formularioParticipante.as_p}}
										</div>
										<div class="d-flex align-items-center justify-content-between mt-4 mb-0">
											<button class="btn btn-primary" type="submit">
												Registrar
											</button>
											<a class="btn btn-danger"  href="{% url 'app_usuarios:Home' %}">
												Cancelar registro
											</a>
										</div>
									</form>						
									{%endif%}
									<form action="{% url 'app_participantes:registro' %}" method="POST">
										{% csrf_token %}
										<div class="form-floating mb-3 formulario">
											{{formularioParticipante.as_p}}
										</div>
										<div class="d-flex align-items-center justify-content-between mt-4 mb-0">
											<button class="btn btn-primary" type="submit">
												Registrar
											</button>
											<a class="btn btn-danger"  href="{% url 'app_usuarios:Home' %}">
												Cancelar registro
											</a>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	</div>
</section>
{% endblock %}