InvasionTropical_Sorteo/InvasionTropical_Sorteo/urls.py
from django.contrib import admin
from django.urls import path,include

# from participantes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('usuarios.urls')),
    path('participantes/',include('participantes.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    
]

InvasionTropical_Sorteo/participantes/urls.py
from django.urls import path
from .views import registrarParticipantes,lista
# from participantes import views
app_name= 'app_participantes'
urlpatterns = [
    path('registro/',registrarParticipantes,name="registro" ),
    path('listadodeventas/',lista,name='lista')

]

InvasionTropical_Sorteo/usuarios/urls.py
from django.urls import path

from .views import bienvenida, home,register_view,salir

app_name='app_usuarios'
urlpatterns = [
    path('',bienvenida,name='bienvenida'),
    path('panel_de_control/',home,name='Home'),
    path('añadir_usuario/',register_view,name='usuario_nuevo'),
    path('salir/',salir, name='salir'),
]

InvasionTropical_Sorteo/templates/home.html
{% extends "base/layout.html" %}
{% block titulo %}
	Invasion Tropical | Inicio
{% endblock %}
{% block contenido %}
	<section>
		<div class="container">			
			<div id="layoutSidenav_content">
	                <main>
	                    <div class="container-fluid px-4">
	                        <h1 class="mt-4">Bienvenido {{user.get_username}}</h1>
	                        <ol class="breadcrumb mb-4">
	                            <li class="breadcrumb-item active">Panel de control</li>
	                        </ol>
	                        <div class="row">
	                            <div class="col-xl-3 col-md-6">
	                                <div class="card bg-primary text-white mb-4">
	                                    <div class="card-body">
											Registrar participante
											<span>
												<i class="fas fa-edit"></i>
											</span>
										</div>
	                                    <div class="card-footer d-flex align-items-center justify-content-between">
	                                        <a class="small text-white stretched-link" href="{% url 'app_participantes:registro' %}">Añadir participante</a>
	                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
	                                    </div>
	                                </div>
	                            </div>
	                            <div class="col-xl-3 col-md-6">
	                                <div class="card bg-warning text-white mb-4">
	                                    <div class="card-body"> Ultimo cupon vendido : {{cupon.nro_cupon}}</div>
	                                    <div class="card-footer d-flex align-items-center justify-content-between">
	                                        <h3 class="small text-white stretched-link" >Cantidad de cupones vendidos: {{ cupones_vendidos }}</h3>
	                                    </div>
	                                </div>
	                            </div>
	                          	 <div class="col-xl-3 col-md-6">
	                                <div class="card bg-success text-white mb-4">
	                                    <div class="card-body">
											Cupones vendidos
											<span>
												<i class="far fa-list-alt"></i>
											</span>
										</div>
	                                    <div class="card-footer d-flex align-items-center justify-content-between">
	                                        <a class="small text-white stretched-link" href="{% url 'app_participantes:lista' %}">
										    	Lista de cupones vendidos
										    </a>
	                                       	<div class="small text-white"><i class="fas fa-angle-right"></i></div>
	                                    </div>

	                                </div>
                                 </div>
	                                 {% if staff == True%}
		                                <div class="col-xl-3 col-md-6">
		                                	<div class="card bg-success text-white mb-4">
			                                    <div class="card-body">
													Añadir usuario
													<span>
														<i class="far fa-list-alt"></i>
													</span>
												</div>
			                                    <div class="card-footer d-flex align-items-center justify-content-between">
			                                        <a class="small text-white stretched-link" href="{% url 'app_usuarios:usuario_nuevo' %}">
												    	Registrar usuario nuevo
												    </a>
			                                       	<div class="small text-white"><i class="fas fa-angle-right"></i></div>
			                                	</div>
			                                </div>
		                                </div>
	                               	{% endif %}

	                        <div class="col-xl-3 col-md-6 table-responsive">
	                          		<table class="table table-bordered">
	                          			<thead class="bg-dark">
	                          				<tr>
	                          					<th class="text-white">
	                          						Cupones vendidos
	                          					</th>
	                          				</tr>
	                          			</thead>
	                          			<tbody>
	                          				{% for cupon in lista_cupon %}
		                          				<tr>
		                          					<td>
		                          						{{ cupon.nro_cupon }}
		                          					</td>
		                          				</tr>
	                          				{% endfor %}
	                          			</tbody>
	                          		</table>
	                          	</div>
	                    </div>
	                </main>
	            </div>
	        </div>
		</div>
	</section>
{% endblock %}

InvasionTropical_Sorteo/templates/home2.html
{% extends "base/layout.html" %}
{% block titulo %}
	Invasion Tropical | Bienvenida
{% endblock %}
{% block contenido %}
<section>
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header bg-dark">
                                <h3 class="text-center font-weight-light my-4 titulo text-white" >
                                    Bienvenido al sistema de registro
                                </h3>
                            </div>
                            <div class="card-body">
                                    <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="btn btn-primary align-items-center " href="{% url 'login' %}">
                                            Ingresar
                                        </a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</section>	 
{% endblock %}